
let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Peace Lily",
    price: 79,
    desc: "This plant can grow in low light, has dark green leaves, and purifies the air.",
    img: "/Users/alekhyakolukuluri/Desktop/Nature-Rabbit-Peace-Lily-Plant.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Spider Plant",
    price: 74,
    desc: "This plant improves air quality, can thrive in almost any setting, and requires little attention. It can also help keep allergies at bay.",
    img: "/Users/alekhyakolukuluri/Desktop/spider_plant.png",
  },
  {
    id: "wuefbncxbsn",
    name: "Rubber Plant",
    price: 190,
    desc: "This plant improves air quality by absorbing bacteria and mold spores along with airborne contaminants.",
    img: "/Users/alekhyakolukuluri/Desktop/Rubber_plant.png",
  },
  {
    id: "thyfhcbcv",
    name: "Elephant Ear Plants",
    price: 150,
    desc: "The elephant ear philodendron plant can filter toxins, allergens, and off-gases to improve air quality.",
    img: "/Users/alekhyakolukuluri/Desktop/Elephant.png",
  },
  {
    id: "jfhgbvsabnscs",
    name: "Snake Plants",
    price: 125,
    desc: "This plant improves air quality at night by taking in carbon dioxide and releasing oxygen.",
    img: "/Users/alekhyakolukuluri/Desktop/snake.png",
  },
  {
    id: "ioytrewrrhndcv",
    name: "English Ivy",
    price: 100,
    desc: "This plant is easy to grow and can survive indoors or outdoors. It absorbs carbon dioxide from the air and removes other harmful chemicals.",
    img: "/Users/alekhyakolukuluri/Desktop/english.png",
  },
  {
    id: "wuefafbncxbsn",
    name: "Golden Pothos",
    price: 159,
    desc: "This leafy plant can remove harmful toxins and improve air quality while also acting as a natural humidifier. It also tolerates low light conditions and can go weeks without watering.",
    img: "/Users/alekhyakolukuluri/Desktop/pothos.png",
  },
  {
    id: "thyfhcbscv",
    name: "Dracaena Warneckii",
    price: 599,
    desc: "This plant absorbs indoor air pollutants like formaldehyde, benzene, trichloroethylene, and carbon dioxide. It also has humidifying and low-maintenance properties.",
    img: "/Users/alekhyakolukuluri/Desktop/Dracaena_Warneckii.png",
  },
  {
    id: "1jfhgbvnscs",
    name: "Erwon Indoor Plant Booster",
    price: 191,
    desc: "Controls pH of these soil as per requirement and rectifies the problems caused by over fertilization or under Fertilisation of the soil.",
    img: "/Users/alekhyakolukuluri/Desktop/f1.png",
  },
  {
    id: "2ioytrhndcv",
    name: "GREENLOOP-All In One Plant Food",
    price: 350,
    desc: "All-In-One product for healthy greener growth of plants. Best suited for balcony (Outdoor) plants, home gardens, Roses. Greener Leaves, more flowering, more growth.",
    img: "/Users/alekhyakolukuluri/Desktop/f2.png",
  },
  {
    id: "3wuefbncxbsn",
    name: "Indian Gardens Plant Fertilizer",
    price: 279,
    desc: "This plant improves air quality by absorbing bacteria and mold spores along with airborne contaminants.",
    img: "/Users/alekhyakolukuluri/Desktop/f3.png",
  },
  {
    id: "4thyfhcbcv",
    name: "Haifa MKP 0-52-34 (1KG)",
    price: 351,
    desc: "Haifa MKP is a fully water-soluble mono-potassium phosphate fertilizer, a highly efficient source of phosphorus and potassium for plants.",
    img: "/Users/alekhyakolukuluri/Desktop/f4.png",
  },
  {
    id: "5jfhgbvsabnscs",
    name: "Nirmal's - Rizamica - Amicorrhizal bio fertilizer.",
    price: 125,
    desc: "Mycorrhizal fungi constitute a group of root obligate biotrophs that exchange mutual benefits in 80% of the plants. These fungal agents are used as a natural biofertilizer",
    img: "/Users/alekhyakolukuluri/Desktop/f5.png",
  },
  {
    id: "6ioytrewrrhndcv",
    name: "Samridhi Crown Mix Micro+ Micronutrient Booster",
    price: 999,
    desc: "Samridhi Crown Mix Micro+ micronutrient fertilizer contains essential and vital nutrients needed by crop, in readily available form.",
    img: "/Users/alekhyakolukuluri/Desktop/f6.png",
  },
  {
    id: "7wuefafbncxbsn",
    name: "GreenLoop Indoor Plant Food",
    price: 299,
    desc: "For INDOOR Plants in SOIL pots / Coco peat / Mix media bed. For faster growth, and healthier greener plants. Special Liquid concentrate. Easy to use.",
    img: "/Users/alekhyakolukuluri/Desktop/f7.png",
  },
  {
    id: "8thyfhcbscv",
    name: "KNR Organic Bio DAP Fertilizer",
    price: 220,
    desc: "KNR Organic DAP is suitable for use as a basal for all crops. It promotes root growth and increases the absorption rate of all nutrients in the soil.",
    img: "/Users/alekhyakolukuluri/Desktop/f8.png",
  },
]